### ISSUE TITLE
payload_hex vs. mic_hex

### ISSUE THREAD

**Issue by jadster** [iotacademy/LoRaPayloadSimulator#1]
What's the difference between payload_hex and mic_hex?

**Comment by maerduq** [comment]
Hi jadster, `payload_hex` is the hexadecimal representation of the payload (also content or body) of the LoRa message, `mic_hex` is the hexadecimal representation of the Message Integrity Code (MIC) of the same LoRa message. More information on LoRa terms you can find here: https://zakelijkforum.kpn.com/lora-forum-16/lora-dictionary-definitions-8495

**Comment by jadster** [comment]
thanks
